
# Object Oriented Programming

# Introduction

Structured oriented programming --- C <br>
Object oriented programming ---- C++ C# JAVA Python<br>
    Exchanges data -- Objects<br>
    need to pass<br>
    need to retrive<br>
    
---

OOP is popular approach to solve a programming problem by creating an object.<br>

An object has two characteristics:
  
  1. Attributes(name,age,colour)<br>
  2. Behaviour(learn,study,singing,dance)<br>
  
  
---

In Python, the concept of OOP follows:

 1. Inheritence<br>
 2. Encapsulation<br>
 3. Ploymorphism<br>
 
 
---

Class:
A class is blueprint of the object


Object:
 Blue print of class or instance of the class or physical activity


---

Methods:

part of class and xcan be called with object


Constructers:

Part of class can be called automatically when the object of class is created

In [14]:
def test():
    print("test() for function")
    return
test()

test() for function


In [ ]:
class ClassName:
    #some functions and variables
    #function--used to perform the specific activity
    #variables--Data(memory)

In [22]:
class Demo:
    def test(self): ## object creation example
        print("test() for the class and method") 
        return
        
obj=Demo()
obj.test() ## object creation example 
           ## Call for method


test() for the class and method


In [23]:
class Demo1():
    def fact(self,n):
        # return the factorial
        fact=1
        while(n!=0):
            fact=fact*n
            n=n-1
        return fact
    
p1=Demo1()
print(p1.fact(6))#720

720


In [25]:
#Method
# def test(self,para1,para2)

class Demo2():
    def Accept(self,p1,p2):
        self.p1=p1
        self.p2=p2
        return
    def Display(self):
        print("p1 = ",p1)
        print("p2 = ",p2)
        
        
c1=Demo2()
c1.Accept(10,20)
c1.Display()

p1 =  <__main__.Demo1 object at 0x03F573D0>


NameError: name 'p2' is not defined

In [30]:
class Demo2():
    def __init__(self,p1,p2):
        self.p1=p1
        self.p2=p2
    def add(self,p1,p2):
        return p1+p2
c1=Demo2(10,20)
print(c1.add(100,200))

300


In [11]:
import numpy as np
lst=[1,2,3,4]
array=np.array(lst)
print(array.shape)
print(array.dtype)


(4,)
int32


a1=np.array([(1,2,3),(4,5,6)])
print(a1.shape)
a2=np.array([(1,2),(3,4),(5,6)])
print(a2.shape)

In [13]:
# RE-shape the given array
#numpy.reshape(arrayname,reshape,order='c)
a1=np.array([(1,2,3),(4,5,6)])
print(a1)
a1.reshape(3,2)

[[1 2 3]
 [4 5 6]]


array([[1, 2],
       [3, 4],
       [5, 6]])

In [12]:

lst = [1,4,5,6,7]
array = np.array(lst)
print(array.shape)
print(array.dtype)

lst=[1,2,3,4]
array = np.array(lst)
print(array)

(5,)
int32
[1 2 3 4]


In [14]:
# Append some data --horizontaly
#hstack(array1,array2)--- will be automatically arranged horizon

a1=np.array([1,2,3])
a2=np.array([4,5,6])
print(np.hstack((a1,a2)))

[1 2 3 4 5 6]


In [16]:
# Append vertically --
# vstack(array1,array2)

a1=np.array([1,2,3])
a2=np.array([4,5,6])
print(np.vstack((a1,a2)))

[[1 2 3]
 [4 5 6]]


In [18]:
#Generate random numbers from numpy
a1=np.random.normal(50,5,10)
print(a1)

[53.6227531  48.2183801  50.32374999 56.88290933 52.26384727 53.11253396
 48.40022107 53.49279122 55.53441497 51.81545458]


In [20]:
# numpy.zeros() and numpy.one()
#numpy.zeros(shape,datatype=,order='c')
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [22]:
np.zeros((2,2),dtype=np.int32)

array([[0, 0],
       [0, 0]])

In [30]:
#np.ones((shape),dtype=np.int32,order='c')
np.ones((4,2),dtype=np.int32)

array([[1, 1],
       [1, 1],
       [1, 1],
       [1, 1]])

In [32]:
A=np.matrix(np.ones((4,4),dtype=np.int64))
print(A)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [34]:
A=np.matrix(np.ones((4,4),dtype=np.int64))
np.asarray(A)[2][3]=5
print(A)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 5]
 [1 1 1 1]]


In [35]:
A=np.matrix(np.ones((4,4),dtype=np.int32))
np.asarray(A)[1][3]=14
np.asarray(A)[3][3]=16
print(A)

[[ 1  1  1  1]
 [ 1  1  1 14]
 [ 1  1  1  1]
 [ 1  1  1 16]]


In [37]:
# arrange()--- particular
#numpy.arrange(start,end,step)
#start - value
#end- value
#step- gap between one value nd other

np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [38]:
np.arange(2,20,2)

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [39]:
np.arange(1,25,2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23])

In [40]:
#Indexing and slicing of numpy
a1=np.array([(1,2,3),(4,5,6)])
print(a1)

[[1 2 3]
 [4 5 6]]


In [43]:
a1=np.array([(1,2,3),(4,5,6)])
print("First Index: ", a1[0])
print("First Index: ", a1[1])

First Index:  [1 2 3]
First Index:  [4 5 6]


In [45]:
a1=np.array([(1,2,3),(4,5,6)])
print("First Index: ", a1[:,1])#slicing row
print("First Index: ", a1[:,2])

First Index:  [2 5]
First Index:  [3 6]


In [47]:
a1=np.array([(1,2,3),(4,5,6)])
print("First Index: ", a1[0])#slicing column
print("First Index: ", a1[1])

First Index:  [1 2 3]
First Index:  [4 5 6]


In [48]:
#some math operatiopns on given random number
# Min
#Max
#Mean
#Median
a1=np.random.normal(5,1,10)
print(a1)
print(np.min(a1))
print(np.max(a1))
print(np.mean(a1))
print(np.median(a1))

[3.99757512 5.14035511 4.2599463  5.76541965 4.66994465 4.75730829
 5.26159069 5.05776742 5.52577514 3.69303346]
3.6930334604975408
5.765419649504332
4.812871581863311
4.9075378536962555


In [49]:
#Multiply of 1D arrays
#numpy.dot(x,y)--
c1=np.array([1,2])
c2=np.array([4,5])
np.dot(c1,c2)

c1=np.array([(1,2),(3,4)])
c2=np.array([(3,4),(1,2)])
np.dot(c1,c2)

b1=np.array([([1,5]),([6,9])])
b2=np.array([([1,3]),([1,6])])
np.matmul(b1,b2)

array([[ 6, 33],
       [15, 72]])

# Pandas Basics
 Python is one of the popular programming language for data analysis<br>    
Python is offering the Lib called Pandas used for importing and analysing pretty much faster and easier also        
Pandas DataFrames        
    
    Data Analysis with Python

In [54]:
import pandas as pd
dict={"Name":["Anil","Akhil","Dinesh","Harsha","Ajay","Kranth"],"EmailID":["anil@gmail.com","akhil@gmail.com","dinesh@gmail.com","harsha@gmail.com","ajay@gmail.com","kranth@gmail.com"],"MobileNumber":[999,888,777,888,777,999],"Address":["Hyd","Hyd","Hyd","Hyd","Hyd","Hyd"],}
b=pd.DataFrame(dict)
print(b)

     Name           EmailID  MobileNumber Address
0    Anil    anil@gmail.com           999     Hyd
1   Akhil   akhil@gmail.com           888     Hyd
2  Dinesh  dinesh@gmail.com           777     Hyd
3  Harsha  harsha@gmail.com           888     Hyd
4    Ajay    ajay@gmail.com           777     Hyd
5  Kranth  kranth@gmail.com           999     Hyd


In [55]:
b.index=["01","02","03","04","05","06"]
print(b)

      Name           EmailID  MobileNumber Address
01    Anil    anil@gmail.com           999     Hyd
02   Akhil   akhil@gmail.com           888     Hyd
03  Dinesh  dinesh@gmail.com           777     Hyd
04  Harsha  harsha@gmail.com           888     Hyd
05    Ajay    ajay@gmail.com           777     Hyd
06  Kranth  kranth@gmail.com           999     Hyd


In [57]:
#Supermarket.csv-Analysis(which product have high % of sp and which have least)

import pandas as pd
products=pd.read_csv('Filename.csv')
print(products)

FileNotFoundError: [Errno 2] File b'Filename.csv' does not exist: b'Filename.csv'

In [58]:
import pandas as pd
product_sellingData=pd.read_csv('FileName.csv',index_col=1)
print(product_sellingData)

FileNotFoundError: [Errno 2] File b'FileName.csv' does not exist: b'FileName.csv'